# Generated by Django 5.0 on 2024-01-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='position',
            field=models.CharField(max_length=50, verbose_name='должность'),
        ),
    ]
