# Generated by Django 5.0 on 2024-01-03 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="employee_id",
        ),
    ]
