# Generated by Django 5.0 on 2024-01-03 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_employee_employee_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Employee"},
        ),
        migrations.RemoveField(
            model_name="employee",
            name="is_busy",
        ),
    ]
