# Generated by Django 5.0 on 2024-01-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employeeuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='chat_id',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='id пользователя в телеграм'),
        ),
    ]
