# Generated by Django 5.0 on 2024-01-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employeeuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='full_name',
            field=models.CharField(default='undefined', max_length=255, verbose_name='ФИО'),
        ),
    ]
