# Generated by Django 5.0 on 2024-01-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employeeuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='is_busy',
            field=models.BooleanField(default=False, help_text='признак занятости сотрудника'),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='электронная почта сотрудника'),
        ),
    ]
